M2-Planet --architecture amd64 \
        -f ../M2-Planet/test/common_amd64/functions/exit.c \
        -f ../M2-Planet/test/common_amd64/functions/file.c \
        -f functions/file_print.c \
        -f ../M2-Planet/test/common_amd64/functions/malloc.c \
        -f functions/calloc.c \
        -f functions/match.c \
        -f functions/string.c \
        -f functions/in_set.c \
        -f functions/require.c \
        -f functions/numerate_number.c \
        -f ../M2-Planet/test/common_amd64/functions/fork.c \
        -f ../M2-Planet/test/common_amd64/functions/execve.c \
        -f ../M2-Planet/test/common_amd64/functions/getcwd.c \
        -f ../M2-Planet/test/common_amd64/functions/chdir.c \
        -f kaem.h \
        -f variable.c \
        -f kaem.c \
        --debug \
        -o kaem.M1

blood-elf --64 -f kaem.M1 -o kaem-footer.M1

M1 -f ../M2-Planet/test/common_amd64/amd64_defs.M1 \
        -f ../M2-Planet/test/common_amd64/libc-core.M1 \
        -f kaem.M1 \
        -f kaem-footer.M1 \
        --LittleEndian \
        --architecture amd64 \
        -o hold

hex2 -f ../M2-Planet/test/common_amd64/ELF-amd64-debug.hex2 \
        -f hold \
        --LittleEndian \
        --architecture amd64 \
        --BaseAddress 0x00600000 \
        -o bin/kaem \
        --exec_enable

rm kaem.M1 kaem-footer.M1 hold
